-- Delete a database that may exist with the name we want to use
DROP DATABASE IF EXISTS nba_stats;

-- Create a database to store our nba data
CREATE DATABASE IF NOT EXISTS nba_stats;

-- Use the newly created database
USE nba_stats;

-- Create a table containing player metadata
CREATE TABLE IF NOT EXISTS PLAYER_METADATA (
    PLAYER_ID INT PRIMARY KEY,
    PLAYER_NAME VARCHAR(100) NOT NULL,
    DOB DATE,
    HEIGHT VARCHAR(10),
    WEIGHT INT,
    POSITION VARCHAR(50),
    DRAFT_YEAR INT,
    DRAFT_ROUND INT,
    DRAFT_NUMBER INT,
    SCHOOL VARCHAR(100),
    COUNTRY VARCHAR(50),
    HEADSHOT_URL TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Create a table to store player game logs
CREATE TABLE IF NOT EXISTS PLAYER_GAME_LOGS (
    GAME_LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    PLAYER_ID INT,
    SEASON_ID VARCHAR(10) NOT NULL,
    GAME_ID VARCHAR(20) NOT NULL,
    GAME_DATE DATE NOT NULL,
    TEAM VARCHAR(10),
    OPPONENT VARCHAR(10),
    HOME_AWAY CHAR(1),
    WL CHAR(1),
    MIN DECIMAL(5,2),
    PTS INT,
    FGM INT,
    FGA INT,
    FG_PCT DECIMAL(5,3),
    FG3M INT,
    FG3A INT,
    FG3_PCT DECIMAL(5,3),
    FTM INT,
    FTA INT,
    FT_PCT DECIMAL(5,3),
    OREB INT,
    DREB INT,
    REB INT,
    AST INT,
    STL INT,
    BLK INT,
    TOV INT,
    PF INT,
    PLUS_MINUS INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY unique_player_game (PLAYER_ID, GAME_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES PLAYER_METADATA(PLAYER_ID)
);

-- Create a View for player career stats
CREATE OR REPLACE VIEW PLAYER_CAREER_STATS AS 
SELECT
    m.PLAYER_ID,
    m.PLAYER_NAME,
    m.POSITION,
    m.HEIGHT,
    m.WEIGHT,
    COUNT(DISTINCT g.SEASON_ID) AS SEASONS,
    COUNT(*) AS GP,
    ROUND(AVG(g.MIN), 1) AS MPG,
    ROUND(AVG(g.PTS), 1) AS PPG,
    ROUND(AVG(g.REB), 1) AS RPG,
    ROUND(AVG(g.AST), 1) AS APG,
    ROUND(AVG(g.STL), 1) AS SPG,
    ROUND(AVG(g.BLK), 1) AS BPG,
    ROUND(AVG(g.TOV), 1) AS TPG, 

    ROUND(SUM(g.FGM) / NULLIF(SUM(g.FGA), 0), 3) AS FG_PCT,
    ROUND(SUM(g.FG3M) / NULLIF(SUM(g.FG3A), 0), 3) AS FG3_PCT,
    ROUND(SUM(g.FTM) / NULLIF(SUM(g.FTA), 0), 3) AS FT_PCT,

    ROUND(SUM(g.PTS) / NULLIF(2 * (SUM(g.FGA) + 0.44 * SUM(g.FTA)), 0), 3) AS TS_PCT,
    ROUND((SUM(g.FGM) + 0.5 * SUM(g.FG3M)) / NULLIF(SUM(g.FGA), 0), 3) AS EFG_PCT

FROM PLAYER_METADATA m
LEFT JOIN PLAYER_GAME_LOGS g ON m.PLAYER_ID = g.PLAYER_ID
GROUP BY m.PLAYER_ID, m.PLAYER_NAME, m.POSITION;

-- Create a View for player season by season stats
CREATE OR REPLACE VIEW PLAYER_SEASON_STATS AS
SELECT 
    g.PLAYER_ID,
    m.PLAYER_NAME,
    g.SEASON_ID,
    COUNT(*) AS GP,
    ROUND(AVG(g.MIN), 1) AS MPG,
    ROUND(AVG(g.FGM), 1) AS FGM,
    ROUND(AVG(g.FGA), 1) AS FGA,
    ROUND(SUM(g.FGM) / NULLIF(SUM(g.FGA), 0), 3) AS FG_PCT,
    ROUND(AVG(g.FG3M), 1) AS FG3M,
    ROUND(AVG(g.FG3A), 1) AS FG3A,
    ROUND(SUM(g.FG3M) / NULLIF(SUM(g.FG3A), 0), 3) AS FG3_PCT,
    ROUND(AVG(g.FTM), 1) AS FTM,
    ROUND(AVG(g.FTA), 1) AS FTA,
    ROUND(SUM(g.FTM) / NULLIF(SUM(g.FTA), 0), 3) AS FT_PCT,
    ROUND(SUM(g.PTS) / NULLIF(2 * (SUM(g.FGA) + 0.44 * SUM(g.FTA)), 0), 3) AS TS_PCT,
    ROUND(AVG(g.REB), 1) AS RPG,
    ROUND(AVG(g.AST), 1) AS APG,
    ROUND(AVG(g.STL), 1) AS SPG,
    ROUND(AVG(g.BLK), 1) AS BPG,
    ROUND(AVG(g.TOV), 1) AS TPG, 
    ROUND(AVG(g.PF), 1) AS PF,
    ROUND(AVG(g.PTS), 1) AS PPG

FROM PLAYER_GAME_LOGS g
JOIN PLAYER_METADATA m ON g.PLAYER_ID = m.PLAYER_ID
GROUP BY g.PLAYER_ID, m.PLAYER_NAME, g.SEASON_ID;

-- Create a View to show player career highs
CREATE OR REPLACE VIEW PLAYER_CAREER_HIGHS AS 
SELECT
    PLAYER_ID,
    MAX(MIN) AS CAREER_HIGH_MIN,
    MAX(PTS) AS CAREER_HIGH_PTS,
    MAX(AST) AS CAREER_HIGH_AST,
    MAX(REB) AS CAREER_HIGH_REB,
    MAX(STL) AS CAREER_HIGH_STL,
    MAX(BLK) AS CAREER_HIGH_BLK,
    MAX(FG3M) AS CAREER_HIGH_3PM,

    MAX(PTS + 0.4 * FGM - 0.7 * FGA - 0.4 * (FTA - FTM) + 0.7 * OREB + 0.3 * DREB + STL + 0.7 * AST + 0.7 * BLK - 0.4 * PF - TOV) AS CAREER_HIGH_GMSCORE

FROM PLAYER_GAME_LOGS
GROUP BY PLAYER_ID;
  

